// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

/** \mainpage FRC 930 Robot Code 2022
 * <h1>Robot Code 2022</h1>
 * <h2>FRC 930</h2>
 * 
 * <p>This is the documentation automatically generated by doxygen for our 2022 robot code.</p>
 * <hr>
 * <p>Have a look at the <a href="annotated.html">Classlist</a> for more detailed information about the project structure.</p>
 * <p>Our code is hosted at <a href="https://github.com/FRC930/Robot2022">Github</a>
 */

package frc.robot;

import edu.wpi.first.wpilibj.TimedRobot;
import edu.wpi.first.wpilibj2.command.CommandScheduler;

public class Robot extends TimedRobot {

  private RobotContainer m_robotContainer;

  private CommandScheduler commandScheduler;

  @Override
  public void robotInit() {
    m_robotContainer = new RobotContainer();
    commandScheduler = CommandScheduler.getInstance();

    m_robotContainer.beginTeleopRunCommands();
  }

  @Override
  public void robotPeriodic() {
    commandScheduler.run();
  }
}
