Robot2022: frc.robot.subsystems.IntakeMotorSubsystem Class Reference
frc.robot.subsystems.IntakeMotorSubsystem Class Reference
Public Member Functions
IntakeMotorSubsystem (int intakeID)
void setMotorSpeed (double speed)
double getMotorSpeed ()
WPI_TalonSRX getIntakeMotor ()
void periodic ()
Constructor & Destructor Documentation
IntakeMotorSubsystem()
frc.robot.subsystems.IntakeMotorSubsystem.IntakeMotorSubsystem (int intakeID)
This constructor initializes the intakeMotorController to the proper hardware
References frc.robot.utilities.GyroUtility.getInstance(), and frc.robot.utilities.GyroUtility.setGyro().
Member Function Documentation
getIntakeMotor()
WPI_TalonSRX frc.robot.subsystems.IntakeMotorSubsystem.getIntakeMotor ()
Returns TalonSRX controller
DriveSubsystem needs the talon for the Pigeon onboard.
Returns
intakeMotor
Referenced by frc.robot.utilities.GyroUtility.setGyro().
getMotorSpeed()
double frc.robot.subsystems.IntakeMotorSubsystem.getMotorSpeed ()
getMotorSpeed
This method returns the intake motor speed
Returns
the current motor speed
setMotorSpeed()
void frc.robot.subsystems.IntakeMotorSubsystem.setMotorSpeed (double speed)
setMotorSpeed
This method sets the intake motor speed to the passed variable
Parameters
speed the speed at which to set the motor
Referenced by frc.robot.commands.intakecommands.intakemotorcommands.RunIntakeMotorsCommand.initialize(), and frc.robot.commands.intakecommands.intakemotorcommands.StopIntakeMotorsCommand.initialize().
The documentation for this class was generated from the following file:
src/main/java/frc/robot/subsystems/IntakeMotorSubsystem.java