Robot2022: IndexerForwardCommand Class Reference
IndexerForwardCommand Class Reference
Public Member Functions
*< h3 > IndexerForwardCommand</h3 > **Sets the motor speed of the indexer **indexer The motor on the indexer * IndexerForwardCommand (IndexerMotorSubsystem indexer, boolean isReversed)
void initialize ()
void execute ()
void end (boolean interrupted)
boolean isFinished ()
Member Function Documentation
end()
void IndexerForwardCommand.end (boolean interrupted)
end
called when the method ends
References frc.robot.subsystems.IndexerMotorSubsystem.stopMotors().
execute()
void IndexerForwardCommand.execute ()
execute
If the loaded sensor does not detect a ball it sets the motor speed to MOTOR_SPEED. If it does detect a ball it sets the motor speed to 0
References frc.robot.utilities.BallSensorUtility.intakeIsTripped(), and frc.robot.utilities.BallSensorUtility.loadedIsTripped().
The documentation for this class was generated from the following file:
src/main/java/frc/robot/commands/IndexerForwardCommand.java