Robot2022: frc.robot.utilities.GyroUtility Class Reference
frc.robot.utilities.GyroUtility Class Reference
Public Member Functions
void setGyro (IntakeMotorSubsystem eSubsystem)
PigeonIMU getGyro ()
Static Public Member Functions
static GyroUtility getInstance ()
Member Function Documentation
getInstance()
static GyroUtility frc.robot.utilities.GyroUtility.getInstance () static
getInstance
Gyro is a singleton, so getInstance returns the instance of the class that the program will use
Returns
the instance
Referenced by frc.robot.subsystems.DriveSubsystem.getHeading(), frc.robot.subsystems.DriveSubsystem.hardReset(), and frc.robot.subsystems.IntakeMotorSubsystem.IntakeMotorSubsystem().
setGyro()
void frc.robot.utilities.GyroUtility.setGyro (IntakeMotorSubsystem eSubsystem)
setGyro
Sets the gyro
getGyro</h3 Gets the gyro
References frc.robot.subsystems.IntakeMotorSubsystem.getIntakeMotor().
Referenced by frc.robot.subsystems.IntakeMotorSubsystem.IntakeMotorSubsystem().
The documentation for this class was generated from the following file:
src/main/java/frc/robot/utilities/GyroUtility.java