Robot2022: frc.robot.utilities.ShooterUtility Class Reference
frc.robot.utilities.ShooterUtility Class Reference
Static Public Member Functions
static void setValuesToShuffleboard (double distance)
static double calculateTopSpeed (double distance)
static double calculateBottomSpeed (double distance)
static double calculateHoodPos (double distance)
Detailed Description
ShooterUtility Calculates how to get a shot in the hub
Member Function Documentation
calculateBottomSpeed()
static double frc.robot.utilities.ShooterUtility.calculateBottomSpeed (double distance) static
calculateBottomSpeed
Returns the new speed for the bottom roller to make the shot.
Parameters
distance the distance from the hub in feet
Returns
the required speed in percent output
Referenced by frc.robot.utilities.ShooterUtility.setValuesToShuffleboard().
calculateHoodPos()
static double frc.robot.utilities.ShooterUtility.calculateHoodPos (double distance) static
calculateHoodPos
Returns the new hood positiion to make the shot.
Parameters
distance the distance from the hub in feet
Returns
the required position in degrees
Referenced by frc.robot.utilities.ShooterUtility.setValuesToShuffleboard().
calculateTopSpeed()
static double frc.robot.utilities.ShooterUtility.calculateTopSpeed (double distance) static
calculateTopSpeed
Returns the new speed for the top roller to make the shot.
Parameters
distance the distance from the hub in feet
Returns
the required speed in percent output
Referenced by frc.robot.utilities.ShooterUtility.setValuesToShuffleboard().
setValuesToShuffleboard()
static void frc.robot.utilities.ShooterUtility.setValuesToShuffleboard (double distance) static
setValuesToShuffleboard
Sends all three calculation results to the shuffleboard.
Parameters
distance the distance from the hub in feet
References frc.robot.utilities.ShooterUtility.calculateBottomSpeed(), frc.robot.utilities.ShooterUtility.calculateHoodPos(), frc.robot.utilities.ShooterUtility.calculateTopSpeed(), frc.robot.utilities.ShuffleboardUtility.getInstance(), and frc.robot.utilities.ShuffleboardUtility.putToShuffleboard().
The documentation for this class was generated from the following file:
src/main/java/frc/robot/utilities/ShooterUtility.java