Robot2022: frc.robot.utilities.ShuffleboardUtility Class Reference
frc.robot.utilities.ShuffleboardUtility Class Reference
Classes
class ShuffleBoardData
enum ShuffleboardKeys
Public Member Functions
void putToShuffleboard (ShuffleboardTab tab, ShuffleboardKeys key, ShuffleBoardData<?> data)
ShuffleBoardData<?> getFromShuffleboard (ShuffleboardKeys key)
void update ()
void addPipelineChooser (String displayName, int value)
int getSelectedPipelineChooser ()
void addAutonOptions (String pathName, CommandBase autoCommand)
Command getSelectedAutonPath ()
void setDefaultAutonOptions (String pathName, CommandBase autoCommand)
Static Public Member Functions
static ShuffleboardUtility getInstance ()
Static Public Attributes
static final ShuffleboardTab driverTab = Shuffleboard.getTab("Driver Tab")
static final ShuffleboardTab testingTab = Shuffleboard.getTab("Testing Tab")
Member Function Documentation
addAutonOptions()
void frc.robot.utilities.ShuffleboardUtility.addAutonOptions (String pathName, CommandBase autoCommand)
addAutonOptions
Adds an option for auton selection
Parameters
pathName name of the path added
autoCommand instance of the command being added
Referenced by frc.robot.commands.autocommands.AutoCommandManager.initCommands().
addPipelineChooser()
void frc.robot.utilities.ShuffleboardUtility.addPipelineChooser (String displayName, int value)
addPipelineChooser
Add a value to the pipeline chooser
Parameters
displayName the name to display
value the index of the pipeline
getFromShuffleboard()
ShuffleBoardData<?> frc.robot.utilities.ShuffleboardUtility.getFromShuffleboard (ShuffleboardKeys key)
getFromShuffleboard
This method gets a value from the shuffleboard
Parameters
key the value to get from the shuffleboard
Returns
the value that the shuffleboard has for the key
getInstance()
static ShuffleboardUtility frc.robot.utilities.ShuffleboardUtility.getInstance () static
getInstance
ShuffleboardUtility is a singleton, so getInstance returns the instance of the class that the program will use
Returns
the instance
Referenced by frc.robot.commands.autocommands.AutoCommandManager.getAutonomousCommand(), frc.robot.commands.autocommands.AutoCommandManager.initCommands(), and frc.robot.utilities.ShooterUtility.setValuesToShuffleboard().
getSelectedAutonPath()
Command frc.robot.utilities.ShuffleboardUtility.getSelectedAutonPath ()
getSelectedAutonPath
Get the option selected on the Shuffleboard
Returns
the selected auton path
Referenced by frc.robot.commands.autocommands.AutoCommandManager.getAutonomousCommand().
getSelectedPipelineChooser()
int frc.robot.utilities.ShuffleboardUtility.getSelectedPipelineChooser ()
getSelectedPipelineChooser
Gets the pipeline that we have selected in the shuffleboard
Returns
the index of the wanted pipeline
putToShuffleboard()
void frc.robot.utilities.ShuffleboardUtility.putToShuffleboard (ShuffleboardTab tab, ShuffleboardKeys key, ShuffleBoardData<?> data)
putToDriverTab
Receives data then inserts it into storage and the shuffleboard widgets on driver tab.
Parameters
key
data
Referenced by frc.robot.utilities.ShooterUtility.setValuesToShuffleboard().
setDefaultAutonOptions()
void frc.robot.utilities.ShuffleboardUtility.setDefaultAutonOptions (String pathName, CommandBase autoCommand)
setDefaultAutonOptions
Sets the default option for auton selection
Parameters
pathName name of the path added
autoCommand instance of the command being added
Referenced by frc.robot.commands.autocommands.AutoCommandManager.initCommands().
update()
void frc.robot.utilities.ShuffleboardUtility.update ()
update
Updates all of the entries on shuffleboard
Gets called in robotPeriodic
The documentation for this class was generated from the following file:
src/main/java/frc/robot/utilities/ShuffleboardUtility.java