Robot2022: frc.robot.subsystems.DriveSubsystem Class Reference
frc.robot.subsystems.DriveSubsystem Class Reference
Public Member Functions
DriveSubsystem (int leftMotorLeaderID, int leftMotorFollowerID, int rightMotorLeaderID, int rightMotorFollowerID)
void refollowDriveMotors ()
void setMotorBrakeMode (NeutralMode brakeMode)
void setVoltages (double leftVoltage, double rightVoltage)
double getLeftVoltage ()
double getRightVoltage ()
DifferentialDriveKinematics getKinematics ()
double calculateLeftFeedforward (double velocity)
double calculateLeftFeedforward (double velocity, double acceleration)
double calculateRightFeedforward (double velocity)
double calculateRightFeedforward (double velocity, double acceleration)
double calculateLeftPID (double speed, double target)
double calculateRightPID (double speed, double target)
DifferentialDriveWheelSpeeds getWheelSpeeds (double xSpeed, double rot)
DifferentialDriveWheelSpeeds getWheelSpeeds ()
double speedToVoltage (double speed)
void setSpeeds (DifferentialDriveWheelSpeeds speeds)
double getLeftEncoder ()
double getRightEncoder ()
double getRawLeftSensorPosition ()
double getRawRightSensorPosition ()
void resetLeftPID ()
void resetRightPID ()
void resetEncoders ()
DifferentialDriveVoltageConstraint getVoltageContraint ()
void drive (double xSpeed, double rot)
double getHeading ()
DifferentialDriveOdometry getOdometry ()
void periodic ()
Static Public Attributes
static final double MAX_ANGULAR_SPEED = Math.PI
static final double HIGH_GEAR_RATIO = 6.3
static final double LOW_GEAR_RATIO = 12.9
static final double TRACK_WIDTH = 0.381 * 2
static final double WHEEL_RADIUS = Units.inchesToMeters(3.875 / 2)
static final int FALCON_ENCODER_RESOLUTION = 2048
static final double MAX_VOLTS = 11.0
static final double DRIVETRAIN_MAX_FREE_SPEED_LOW
static final double DRIVETRAIN_MAX_FREE_SPEED_HIGH
Detailed Description
DriveSubsystem
DriveSubsystem represents the drivetrain to our code
Constructor & Destructor Documentation
DriveSubsystem()
frc.robot.subsystems.DriveSubsystem.DriveSubsystem (int leftMotorLeaderID, int leftMotorFollowerID, int rightMotorLeaderID, int rightMotorFollowerID)
Constructs a differential drive object. Sets the encoder distance per pulse and resets the gyro.
DriveSubsystem
Constructs a differential drive object. Sets the encoder distance per pulse and resets the gyro.
Parameters
leftMotorLeaderID the ID of the left motor leader
leftMotorFollowerID the ID of the left motor follower
rightMotorLeaderID the ID of the right motor leader
rightMotorFollowerID the ID of the right motor follower
Member Function Documentation
calculateLeftFeedforward() [1/2]
double frc.robot.subsystems.DriveSubsystem.calculateLeftFeedforward (double velocity)
Calculate the feedforward with the left controller
Parameters
velocity the velocity for which to calculate feedforward
Returns
the output of the feedforward controller (in volts)
calculateLeftFeedforward() [2/2]
double frc.robot.subsystems.DriveSubsystem.calculateLeftFeedforward (double velocity, double acceleration)
Calculate the feedforward with the left controller Overloaded method to allow the input of acceleration
Parameters
velocity the velocity for which to calculate feedforward
Returns
the output of the feedforward contoller (in volts)
calculateLeftPID()
double frc.robot.subsystems.DriveSubsystem.calculateLeftPID (double speed, double target)
Calculate the left PID values
Parameters
speed the current speed
target the target speed
Returns
the PID corrected speed
calculateRightFeedforward() [1/2]
double frc.robot.subsystems.DriveSubsystem.calculateRightFeedforward (double velocity)
Calculate the feedforward with the right controller
Parameters
velocity the velocity for which to calculate feedforward
Returns
the output of the feedforward controller (in volts)
calculateRightFeedforward() [2/2]
double frc.robot.subsystems.DriveSubsystem.calculateRightFeedforward (double velocity, double acceleration)
Calculate the feedforward with the right controller Overloaded method to allow the input of acceleration
Parameters
velocity the velocity for which to calculate feedforward
Returns
the output of the feedforward controller (in volts)
calculateRightPID()
double frc.robot.subsystems.DriveSubsystem.calculateRightPID (double speed, double target)
Calculate the left PID values
Parameters
speed the current speed
target the target speed
Returns
the PID corrected speed
drive()
void frc.robot.subsystems.DriveSubsystem.drive (double xSpeed, double rot)
Drives the robot with the given linear velocity and angular velocity.
Parameters
xSpeed Linear velocity in m/s.
rot Angular velocity in rad/s.
References frc.robot.subsystems.DriveSubsystem.setSpeeds().
getHeading()
double frc.robot.subsystems.DriveSubsystem.getHeading ()
Returns the heading of the gyro.
Returns
the heading of the gyro.
References frc.robot.utilities.GyroUtility.getGyro(), and frc.robot.utilities.GyroUtility.getInstance().
getKinematics()
DifferentialDriveKinematics frc.robot.subsystems.DriveSubsystem.getKinematics ()
getKinematics
Gets the kinematics
Returns
the kinematics used by the drivetrain
Referenced by frc.robot.commands.autocommands.paths.TaxiOneBall.TaxiOneBall(), and frc.robot.commands.autocommands.paths.TaxiOneBallAim.TaxiOneBallAim().
getLeftEncoder()
double frc.robot.subsystems.DriveSubsystem.getLeftEncoder ()
Gets the reading from the left encoder
Returns
the encoder speed
Referenced by frc.robot.subsystems.DriveSubsystem.getWheelSpeeds().
getLeftVoltage()
double frc.robot.subsystems.DriveSubsystem.getLeftVoltage ()
getLeftVoltage
Gets the voltage of the left motor
Returns
the left motor output voltage
getOdometry()
DifferentialDriveOdometry frc.robot.subsystems.DriveSubsystem.getOdometry ()
Drives the robot with the given linear velocity and angular velocity.
Returns
m_odometry .
Referenced by frc.robot.commands.autocommands.ResetAutonomousCommand.ResetAutonomousCommand(), frc.robot.commands.autocommands.paths.TaxiOneBall.TaxiOneBall(), and frc.robot.commands.autocommands.paths.TaxiOneBallAim.TaxiOneBallAim().
getRawLeftSensorPosition()
double frc.robot.subsystems.DriveSubsystem.getRawLeftSensorPosition ()
getRawLeftSensorPosition
This method gets the position of the right encoder
Returns
the position of the right encoder in raw encoder units
See also
getSelectedSensorPosition()
Referenced by frc.robot.subsystems.DriveSubsystem.periodic().
getRawRightSensorPosition()
double frc.robot.subsystems.DriveSubsystem.getRawRightSensorPosition ()
getRawRightSensorPosition
This method gets the position of the right encoder
Returns
the position of the left encoder in raw encoder units
See also
getSelectedSensorPosition()
Referenced by frc.robot.subsystems.DriveSubsystem.periodic().
getRightEncoder()
double frc.robot.subsystems.DriveSubsystem.getRightEncoder ()
Gets the reading from the right encoder
Returns
the encoder speed
Referenced by frc.robot.subsystems.DriveSubsystem.getWheelSpeeds().
getRightVoltage()
double frc.robot.subsystems.DriveSubsystem.getRightVoltage ()
getRightVoltage
Gets the voltage of the right motor
Returns
the right motor output voltage
getVoltageContraint()
DifferentialDriveVoltageConstraint frc.robot.subsystems.DriveSubsystem.getVoltageContraint ()
getVoltageConstraint
Get the voltage constraint used for autonomous
Returns
the autonomous voltage constraint
getWheelSpeeds() [1/2]
DifferentialDriveWheelSpeeds frc.robot.subsystems.DriveSubsystem.getWheelSpeeds ()
Returns the speeds in the differential drive Overloaded getWheelSpeed that just gets the motor encoder position
Returns
A DifferentialDriveWheelSpeeds object, has the rotations of the left and right wheels
References frc.robot.subsystems.DriveSubsystem.getLeftEncoder(), and frc.robot.subsystems.DriveSubsystem.getRightEncoder().
getWheelSpeeds() [2/2]
DifferentialDriveWheelSpeeds frc.robot.subsystems.DriveSubsystem.getWheelSpeeds (double xSpeed, double rot)
Convert stick input values to wheel speeds
Parameters
xSpeed speed stick
rot rotation stick
Returns
the wheel speeds from the sticks
periodic()
void frc.robot.subsystems.DriveSubsystem.periodic ()
periodic
Called every loop iteration when the scheduler runs.
This will update the odometry for automous
See also
super periodic method
References frc.robot.utilities.GyroUtility.getGyro(), frc.robot.utilities.GyroUtility.getInstance(), frc.robot.subsystems.DriveSubsystem.getRawLeftSensorPosition(), and frc.robot.subsystems.DriveSubsystem.getRawRightSensorPosition().
resetEncoders()
void frc.robot.subsystems.DriveSubsystem.resetEncoders ()
resetEncoders
Resets the encoders to zero. This will affect the selected sensor position, but not the absolute position
Referenced by frc.robot.commands.autocommands.ResetAutonomousCommand.initialize().
resetLeftPID()
void frc.robot.subsystems.DriveSubsystem.resetLeftPID ()
resetLeftPID
This method resets the left PID controller (only useful when using integral and derivative)
Referenced by frc.robot.commands.Ramsete930Command.initialize().
resetRightPID()
void frc.robot.subsystems.DriveSubsystem.resetRightPID ()
resetRightPID
This method resets the right PID controller (only useful when using integral and derivative)
Referenced by frc.robot.commands.Ramsete930Command.initialize().
setMotorBrakeMode()
void frc.robot.subsystems.DriveSubsystem.setMotorBrakeMode (NeutralMode brakeMode)
setMototBreakMode
Sets left and right motors to a certain breakmode: auto is brake; teleop is coast
Parameters
brakeMode
Referenced by frc.robot.RobotContainer.beginAutoRunCommands(), and frc.robot.RobotContainer.beginTeleopRunCommands().
setSpeeds()
void frc.robot.subsystems.DriveSubsystem.setSpeeds (DifferentialDriveWheelSpeeds speeds)
Sets the desired wheel speeds.
Parameters
speeds The desired wheel speeds.
References frc.robot.subsystems.DriveSubsystem.setVoltages().
Referenced by frc.robot.subsystems.DriveSubsystem.drive().
setVoltages()
void frc.robot.subsystems.DriveSubsystem.setVoltages (double leftVoltage, double rightVoltage)
setVoltages
Sets the voltages of the drivetrain to the passed values
Parameters
leftVoltage the left voltage
rightVoltage the right voltage
Referenced by frc.robot.subsystems.DriveSubsystem.setSpeeds(), frc.robot.RobotContainer.stopSubsystems(), frc.robot.commands.autocommands.paths.TaxiOneBall.TaxiOneBall(), and frc.robot.commands.autocommands.paths.TaxiOneBallAim.TaxiOneBallAim().
speedToVoltage()
double frc.robot.subsystems.DriveSubsystem.speedToVoltage (double speed)
Convert speed to voltage
Parameters
speed the speed at which the motor should turn
Returns
the volatage at which to run the motor
Member Data Documentation
DRIVETRAIN_MAX_FREE_SPEED_HIGH
final double frc.robot.subsystems.DriveSubsystem.DRIVETRAIN_MAX_FREE_SPEED_HIGH static
Initial value:
= 6380.0
            / 60.0
            / HIGH_GEAR_RATIO
            * (WHEEL_RADIUS * 2 * Math.PI)
DRIVETRAIN_MAX_FREE_SPEED_LOW
final double frc.robot.subsystems.DriveSubsystem.DRIVETRAIN_MAX_FREE_SPEED_LOW static
Initial value:
= 6380.0
            / 60.0
            / LOW_GEAR_RATIO
            * (WHEEL_RADIUS * 2 * Math.PI)
The documentation for this class was generated from the following file:
src/main/java/frc/robot/subsystems/DriveSubsystem.java