Robot2022: frc.robot.commands.autocommands.ResetAutonomousCommand Class Reference
frc.robot.commands.autocommands.ResetAutonomousCommand Class Reference
Public Member Functions
ResetAutonomousCommand (Pose2d startingPose, DriveSubsystem dSubsystem)
void initialize ()
boolean isFinished ()
Detailed Description
ResetAutonomousCommand
Resets the gyro and encoders
Constructor & Destructor Documentation
ResetAutonomousCommand()
frc.robot.commands.autocommands.ResetAutonomousCommand.ResetAutonomousCommand (Pose2d startingPose, DriveSubsystem dSubsystem)
ResetAutonomousCommand
Parameters
startingPose
dSubsystem
References frc.robot.subsystems.DriveSubsystem.getOdometry().
Member Function Documentation
initialize()
void frc.robot.commands.autocommands.ResetAutonomousCommand.initialize ()
Called when the command is initially scheduled.
References frc.robot.utilities.GyroUtility.getGyro(), frc.robot.utilities.GyroUtility.getInstance(), and frc.robot.subsystems.DriveSubsystem.resetEncoders().
isFinished()
boolean frc.robot.commands.autocommands.ResetAutonomousCommand.isFinished ()
Returns true when the command should end.
The documentation for this class was generated from the following file:
src/main/java/frc/robot/commands/autocommands/ResetAutonomousCommand.java