Robot2022: frc.robot.commands.autocommands.AutoCommandManager Class Reference
frc.robot.commands.autocommands.AutoCommandManager Class Reference
Classes
enum subNames
Public Member Functions
void addSubsystem (subNames SubNames, Subsystem subsystem)
void initCommands ()
Command getAutonomousCommand ()
Detailed Description
AutonomouseCommandManager
Manages the autonomous paths by creating an instance of them and putting them into the Shuffleboard.
Member Function Documentation
addSubsystem()
void frc.robot.commands.autocommands.AutoCommandManager.addSubsystem (subNames SubNames, Subsystem subsystem)
Adds a subbsystem to the subystem map
Parameters
SubNames
subsbystem
getAutonomousCommand()
Command frc.robot.commands.autocommands.AutoCommandManager.getAutonomousCommand ()
Gets the autonomous path that is selected in the Shuffleboard
Returns
The selected autonomous commandl
References frc.robot.utilities.ShuffleboardUtility.getInstance(), and frc.robot.utilities.ShuffleboardUtility.getSelectedAutonPath().
Referenced by frc.robot.RobotContainer.autoSimInit(), and frc.robot.RobotContainer.getAutonomousCommand().
initCommands()
void frc.robot.commands.autocommands.AutoCommandManager.initCommands ()
Creates instances of each autonomous path command
References frc.robot.utilities.ShuffleboardUtility.addAutonOptions(), frc.robot.utilities.ShuffleboardUtility.getInstance(), and frc.robot.utilities.ShuffleboardUtility.setDefaultAutonOptions().
The documentation for this class was generated from the following file:
src/main/java/frc/robot/commands/autocommands/AutoCommandManager.java