Robot2022: frc.robot.commands.autocommands.paths.AutoTest2 Class Reference
frc.robot.commands.autocommands.paths.AutoTest2 Class Reference
Public Member Functions
AutoTest2 (DriveSubsystem dSubsystem)
double inchesToMeters (double inches)
Public Member Functions inherited from frc.robot.utilities.PathPlannerSequentialCommandGroupUtility
void addTrajectory (Trajectory traj)
List< Trajectory > getTrajectories ()
Constructor & Destructor Documentation
AutoTest2()
frc.robot.commands.autocommands.paths.AutoTest2.AutoTest2 (DriveSubsystem dSubsystem)
Default path constructor
Parameters
dSubsystem
References frc.robot.subsystems.DriveSubsystem.getKinematics(), frc.robot.subsystems.DriveSubsystem.getOdometry(), frc.robot.utilities.DifferentialDriveOdometry930.getPoseMeters(), and frc.robot.subsystems.DriveSubsystem.setVoltages().
Member Function Documentation
inchesToMeters()
double frc.robot.commands.autocommands.paths.AutoTest2.inchesToMeters (double inches)
Converts Inches into meters
Parameters
inches
Returns
meters
The documentation for this class was generated from the following file:
src/main/java/frc/robot/commands/autocommands/paths/AutoTest2.java