Robot2022: frc.robot.commands.IndexerForwardCommand Class Reference
frc.robot.commands.IndexerForwardCommand Class Reference
Public Member Functions
IndexerForwardCommand (IndexerMotorSubsystem _motor)
void execute ()
void end (boolean interrupted)
boolean isFinished ()
Member Function Documentation
execute()
void frc.robot.commands.IndexerForwardCommand.execute ()
execute
If the catapult sensor does not detect a ball it sets the motor speed to MOTOR_SPEED. If it does detect a ball it sets the motor speed to 0
References frc.robot.utilities.BallSensorUtility.catapultIsTripped(), frc.robot.utilities.BallSensorUtility.indexerIsTripped(), and frc.robot.subsystems.IndexerMotorSubsystem.setMotorSpeed().
The documentation for this class was generated from the following file:
src/main/java/frc/robot/commands/IndexerForwardCommand.java