Robot2022: frc.robot.utilities.DifferentialDriveOdometry930 Class Reference
frc.robot.utilities.DifferentialDriveOdometry930 Class Reference
Public Member Functions
DifferentialDriveOdometry930 (Rotation2d gyroAngle, Pose2d initialPoseMeters)
DifferentialDriveOdometry930 (Rotation2d gyroAngle)
void resetPosition (Pose2d poseMeters, Rotation2d gyroAngle)
void resetRotation (Rotation2d gyroAngle)
Pose2d getPoseMeters ()
Pose2d update (Rotation2d gyroAngle, double leftDistanceMeters, double rightDistanceMeters)
Detailed Description
Class for differential drive odometry. Odometry allows you to track the robot's position on the field over the course of a match using readings from 2 encoders and a gyroscope.
Teams can use odometry during the autonomous period for complex tasks like path following. Furthermore, odometry can be used for latency compensation when using computer-vision systems.
It is important that you reset your encoders to zero before using this class. Any subsequent pose resets also require the encoders to be reset to zero.
Constructor & Destructor Documentation
DifferentialDriveOdometry930() [1/2]
frc.robot.utilities.DifferentialDriveOdometry930.DifferentialDriveOdometry930 (Rotation2d gyroAngle, Pose2d initialPoseMeters)
Constructs a DifferentialDriveOdometry object.
Parameters
gyroAngle The angle reported by the gyroscope.
initialPoseMeters The starting position of the robot on the field.
DifferentialDriveOdometry930() [2/2]
frc.robot.utilities.DifferentialDriveOdometry930.DifferentialDriveOdometry930 (Rotation2d gyroAngle)
Constructs a DifferentialDriveOdometry object with the default pose at the origin.
Parameters
gyroAngle The angle reported by the gyroscope.
Member Function Documentation
getPoseMeters()
Pose2d frc.robot.utilities.DifferentialDriveOdometry930.getPoseMeters ()
Returns the position of the robot on the field.
Returns
The pose of the robot (x and y are in meters).
Referenced by frc.robot.commands.autocommands.paths.AutoTest1.AutoTest1(), frc.robot.commands.autocommands.paths.AutoTest2.AutoTest2(), frc.robot.commands.autocommands.paths.AutoTestFull.AutoTestFull(), frc.robot.commands.autocommands.paths.CompPath1.CompPath1(), frc.robot.commands.autocommands.paths.DefaultAutoPathCommand.DefaultAutoPathCommand(), frc.robot.commands.autocommands.paths.ShootMoveShoot.ShootMoveShoot(), and frc.robot.commands.autocommands.paths.TerminalPickup.TerminalPickup().
resetPosition()
void frc.robot.utilities.DifferentialDriveOdometry930.resetPosition (Pose2d poseMeters, Rotation2d gyroAngle)
Resets the robot's position on the field.
You NEED to reset your encoders (to zero) when calling this method.
The gyroscope angle does not need to be reset here on the user's robot code. The library automatically takes care of offsetting the gyro angle.
Parameters
poseMeters The position on the field that your robot is at.
gyroAngle The angle reported by the gyroscope.
Referenced by frc.robot.subsystems.DriveSubsystem.hardReset().
resetRotation()
void frc.robot.utilities.DifferentialDriveOdometry930.resetRotation (Rotation2d gyroAngle)
Resets the robot's rotation.
You NEED to reset your encoders (to zero) when calling this method.
The gyroscope angle does not need to be reset here on the user's robot code. The library automatically takes care of offsetting the gyro angle.
Parameters
gyroAngle The angle reported by the gyroscope.
Referenced by frc.robot.subsystems.DriveSubsystem.softReset().
update()
Pose2d frc.robot.utilities.DifferentialDriveOdometry930.update (Rotation2d gyroAngle, double leftDistanceMeters, double rightDistanceMeters)
Updates the robot position on the field using distance measurements from encoders. This method is more numerically accurate than using velocities to integrate the pose and is also advantageous for teams that are using lower CPR encoders.
Parameters
gyroAngle The angle reported by the gyroscope.
leftDistanceMeters The distance traveled by the left encoder.
rightDistanceMeters The distance traveled by the right encoder.
Returns
The new pose of the robot.
The documentation for this class was generated from the following file:
src/main/java/frc/robot/utilities/DifferentialDriveOdometry930.java