Robot2022: frc.robot.commands.LEDCommand Class Reference
frc.robot.commands.LEDCommand Class Reference
Classes
enum LEDPatterns
Public Member Functions
LEDCommand (LEDSubsystem subsystem, LEDPatterns pattern)
void initialize ()
void execute ()
void end (boolean interrupted)
boolean isFinished ()
void easyInit ()
void easy ()
void everyOtherInit ()
void onEveryOtherInit ()
void everyOther ()
void idlePatternInit ()
void idlePattern ()
void intakePatternInit ()
void intakePattern ()
void shooterPatternInit ()
void shooterPattern ()
void ledsOff ()
void OnEveryOther ()
void SolidLEDs ()
Member Function Documentation
everyOther()
void frc.robot.commands.LEDCommand.everyOther ()
sets the LED pattern to: 10101010101010......
(0 being off, 1 being blue)
Clears the LED strip and sets all LED's to off
Sets the LED pattern to: 01010101010101......
(0 being off, 1 being blue)
sets the LED pattern to: 10101010101010......
(0 being off, 1 being red)
clears the LED strip and sets all LED's to off
Sets the LED pattern to: 01010101010101......
(0 being off, 1 being red)
References frc.robot.subsystems.LEDSubsystem.getBufferLength().
idlePattern()
void frc.robot.commands.LEDCommand.idlePattern ()
sets the LED pattern to: 10101010101010......
(0 being off, 1 being yellow)
sets the LED pattern to: 01010101010101......
(0 being off, 1 being yellow)
References frc.robot.subsystems.LEDSubsystem.getBufferLength().
OnEveryOther()
void frc.robot.commands.LEDCommand.OnEveryOther ()
sets the LED pattern to: 10101010101010......
(0 being off, 1 being blue)
Clears the LED strip and sets all LED's to off
Sets the LED pattern to: 01010101010101......
(0 being off, 1 being blue)
sets the LED pattern to: 10101010101010......
(0 being off, 1 being red)
clears the LED strip and sets all LED's to off
Sets the LED pattern to: 01010101010101......
(0 being off, 1 being red)
References frc.robot.subsystems.LEDSubsystem.getBufferLength().
The documentation for this class was generated from the following file:
src/main/java/frc/robot/commands/LEDCommand.java