Robot2022: frc.robot.commands.autocommands.paths.TaxiOneBallAim Class Reference
frc.robot.commands.autocommands.paths.TaxiOneBallAim Class Reference
Public Member Functions
TaxiOneBallAim (DriveSubsystem driveSubsystem, IntakePistonSubsystem intakePistonSubsystem, IntakeMotorSubsystem intakeMotorSubsystem, ShooterSubsystem shooterSubsystem, ShooterHoodSubsystem shooterHoodSubsystem, IndexerMotorSubsystem indexerMotorSubsystem)
Public Member Functions inherited from frc.robot.commands.autocommands.AutoBase
*< h3 > TerminalPickup</h3 > **Four ball auto.Starts near the center of the moves *to moves back to and shoots.**driveSubsystem *intakePistonSubsystem *intakeMotorSubsystem *visionCameraSubsystem *catapultSubsystem * AutoBase (DriveSubsystem driveSubsystem, Trajectory initialTrajectory)
Public Member Functions inherited from frc.robot.utilities.PathPlannerSequentialCommandGroupUtility
void addTrajectory (Trajectory traj)
List< Trajectory > getTrajectories ()
Additional Inherited Members
Protected Attributes inherited from frc.robot.commands.autocommands.AutoBase
Trajectory m_initialTrajectory
Constructor & Destructor Documentation
TaxiOneBallAim()
frc.robot.commands.autocommands.paths.TaxiOneBallAim.TaxiOneBallAim (DriveSubsystem driveSubsystem, IntakePistonSubsystem intakePistonSubsystem, IntakeMotorSubsystem intakeMotorSubsystem, ShooterSubsystem shooterSubsystem, ShooterHoodSubsystem shooterHoodSubsystem, IndexerMotorSubsystem indexerMotorSubsystem)
TaxiOneBall
Exits the tarmac and shoots.
Parameters
driveSubsystem
indexerMotorSubsystem
shooterSubsystem
intakeMotorSubsystem
intakePistonSubsystem
catapultSubsystem
References frc.robot.subsystems.DriveSubsystem.getKinematics(), frc.robot.subsystems.DriveSubsystem.getOdometry(), and frc.robot.subsystems.DriveSubsystem.setVoltages().
The documentation for this class was generated from the following file:
src/main/java/frc/robot/commands/autocommands/paths/TaxiOneBallAim.java