Robot2022: frc.robot.subsystems.IntakePistonSubsystem Class Reference
frc.robot.subsystems.IntakePistonSubsystem Class Reference
Public Member Functions
*< h3 > IntakePistonSubsystem</h3 > **Handles the pistons that raise and lower the intake.**solenoidID ID for the first intake solenoid that retracts * IntakePistonSubsystem (int solenoidID)
void setIntakePistonState (boolean state)
boolean getIntakeSolenoidOneState ()
Member Function Documentation
getIntakeSolenoidOneState()
boolean frc.robot.subsystems.IntakePistonSubsystem.getIntakeSolenoidOneState ()
getIntakeSolenoidState
Reads the state of the intake piston
Returns
the piston state
setIntakePistonState()
void frc.robot.subsystems.IntakePistonSubsystem.setIntakePistonState (boolean state)
setIntakePistonState
Sets the shifter to the passed state
Parameters
state the state to write to the piston
Referenced by frc.robot.commands.intakecommands.intakePistonCommands.EngageIntakePistonsCommand.end(), frc.robot.commands.intakecommands.intakePistonCommands.DisengageIntakePistonsCommand.initialize(), and frc.robot.commands.intakecommands.intakePistonCommands.EngageIntakePistonsCommand.initialize().
The documentation for this class was generated from the following file:
src/main/java/frc/robot/subsystems/IntakePistonSubsystem.java