Robot2022: frc.robot.RobotContainer Class Reference
frc.robot.RobotContainer Class Reference
Public Member Functions
void beginTeleopRunCommands ()
void startCamera ()
Command getAutonomousCommand ()
void beginAutoRunCommands ()
void testInit ()
void testPeriodic ()
void testExit ()
void stopSubsystems ()
void robotSimInit ()
void autoSimInit ()
void robotSimPeriodic ()
void autoSimPeriodic ()
void simPeriodic ()
void disabledInit ()
Static Public Attributes
static final int CAMERA_WIDTH = 160
static final int CAMERA_HEIGHT = 120
static final int CAMERA_FPS = 30
Member Function Documentation
autoSimInit()
void frc.robot.RobotContainer.autoSimInit ()
autoSimInit
Begins autonomous simulation. Resets position and timer.
References frc.robot.commands.autocommands.AutoCommandManager.getAutonomousCommand().
autoSimPeriodic()
void frc.robot.RobotContainer.autoSimPeriodic ()
autoSimPeriodic
Updates the position of the simulated robot autonomous periodically.
Referenced by frc.robot.Robot.autonomousPeriodic().
beginAutoRunCommands()
void frc.robot.RobotContainer.beginAutoRunCommands ()
beginAutoRunCommands
Prepares the robot for autonomous.
References frc.robot.subsystems.DriveSubsystem.setMotorBrakeMode().
beginTeleopRunCommands()
void frc.robot.RobotContainer.beginTeleopRunCommands ()
beginTeleopRunCommands
Runs when the robot is enabled in teleop mode.
This gets the command scheduler and sets up buttons
References frc.robot.subsystems.DriveSubsystem.setMotorBrakeMode().
disabledInit()
void frc.robot.RobotContainer.disabledInit ()
disabledInit
Robot initialization when disabled.
getAutonomousCommand()
Command frc.robot.RobotContainer.getAutonomousCommand ()
getAutonomousCommand
Gets the selected autonomous command.
References frc.robot.commands.autocommands.AutoCommandManager.getAutonomousCommand().
robotSimInit()
void frc.robot.RobotContainer.robotSimInit ()
robotSimInit
Runs when the robot is initialized in simulation.
robotSimPeriodic()
void frc.robot.RobotContainer.robotSimPeriodic ()
robotSimPeriodic
Updates simulated robot periodically.
simPeriodic()
void frc.robot.RobotContainer.simPeriodic ()
simPeriodic
Updates simulation
startCamera()
void frc.robot.RobotContainer.startCamera ()
startCamera
Starts up the driver camera.
stopSubsystems()
void frc.robot.RobotContainer.stopSubsystems ()
stopSubsystems
Sets the intake and drive motors to 0.
References frc.robot.subsystems.DriveSubsystem.setVoltages(), and frc.robot.subsystems.IndexerMotorSubsystem.stopMotors().
Referenced by frc.robot.RobotContainer.testInit().
testExit()
void frc.robot.RobotContainer.testExit ()
testExit
Runs when robot exits test mode.
References frc.robot.subsystems.EndgameMotorSubsystem.refollowEndgameMotors(), and frc.robot.subsystems.ShooterSubsystem.refollowShooterMotors().
testInit()
void frc.robot.RobotContainer.testInit ()
testInit
Initializes the robot for test mode.
References frc.robot.subsystems.EndgameMotorSubsystem.refollowEndgameMotors(), and frc.robot.RobotContainer.stopSubsystems().
testPeriodic()
void frc.robot.RobotContainer.testPeriodic ()
testPeriodic
Test mode periodic.
References frc.robot.subsystems.EndgamePistonSubsystem.closed(), frc.robot.ControllerManager.getAButton(), frc.robot.ControllerManager.getBButton(), frc.robot.ControllerManager.getLeftBumper(), frc.robot.ControllerManager.getXButton(), frc.robot.ControllerManager.getYButton(), frc.robot.subsystems.EndgamePistonSubsystem.open(), frc.robot.subsystems.EndgameMotorSubsystem.refollowEndgameMotors(), and frc.robot.subsystems.EndgameMotorSubsystem.setMotorSpeed().
The documentation for this class was generated from the following file:
src/main/java/frc/robot/RobotContainer.java